import type { AssistantCapability } from '../types';

export const ASSISTANT_CAPABILITIES_PART_1: AssistantCapability[] = [
  {
    id: 'home',
    name: 'Home',
    status: 'implemented',
    description: 'Signed-in home feed with Score snapshot, Governance shortcut, post composer with formatting (including line spacing), Edit post for the author, and post actions Like · Comment · Repost · Publish to….',
    howTo: 'Open Home from the bottom nav. Share a post from the composer; Bold, Italic, Underline, lists, and line spacing are available while the composer is focused. On any post: Like, Comment (discussion under the post), Repost (plain or with thoughts into your own feed), or Publish to… (external networks when you are the author on the official Civizen org account). The author (or the organization account that published it) can Edit post at any time; Edited appears next to the time after a change. Repost keeps a link to the original — it does not copy the text.',
    routes: ['/'],
    roles: ['member', 'citizen', 'verified_member', 'certified', 'moderator', 'admin', 'founder'],
    relatedCapabilities: ['score', 'governance', 'messaging'],
    aliases: ['feed', 'timeline'],
    sourceRefs: ['src/pages/Home.tsx', 'src/lib/main-nav.ts'],
  },
  {
    id: 'study',
    name: 'Study',
    status: 'implemented',
    description:
      'Learning hub for civic materials such as the Community Governance Charter, laws, and related study domains. Distinct from Learning Commons.',
    howTo: 'Open Study from the bottom navigation.',
    routes: ['/study', '/law'],
    roles: ['guest', 'member'],
    relatedCapabilities: ['governance_charter', 'knowledge_spaces'],
    aliases: ['learning hub', 'courses'],
    sourceRefs: ['src/lib/study.ts', 'src/lib/main-nav.ts', 'docs/assistant/civizen-assistant-cheatsheet.md'],
  },
  {
    id: 'contribute_hub',
    name: 'Contribute',
    status: 'implemented',
    description:
      'Participation gateway asking how you would like to contribute today. Ways, Community, Knowledge, and Your Impact.',
    howTo: 'Open Contribute from the bottom navigation.',
    routes: ['/contribute'],
    roles: ['member'],
    relatedCapabilities: ['opportunities', 'community_challenges', 'knowledge_spaces', 'my_contributions', 'matters'],
    aliases: ['contribution hub', 'how can I contribute'],
    sourceRefs: [
      'src/lib/contribute-lanes.ts',
      'docs/04-operations/dev/contribute-page.md',
      'docs/assistant/civizen-assistant-cheatsheet.md',
    ],
  },
  {
    id: 'opportunities',
    name: 'Opportunities',
    status: 'implemented',
    description:
      'Short verifiable pieces of work. Education-to-Contribution lives under Contribute > Opportunities. Apply, complete work, submit evidence, and get it verified.',
    howTo:
      'Open Contribute > Opportunities. Open an opportunity, apply, do the work, then submit evidence for verification.',
    routes: ['/contribute/professional', '/contribute/professional/new'],
    roles: ['member'],
    relatedCapabilities: ['my_contributions', 'score', 'community_challenges', 'knowledge_gaps'],
    aliases: ['professional listings', 'open tasks', 'professional skills', 'tasks'],
    sourceRefs: [
      'src/lib/contribute-lanes.ts',
      'src/pages/contribute/ProfessionalOpportunities.tsx',
      'docs/04-operations/dev/contribute-page.md',
    ],
  },
  {
    id: 'community_challenges',
    name: 'Community Challenges',
    status: 'implemented',
    description:
      'Name a local problem, collect proposals, choose one solution, implement it through a Project, and keep a Solution Record. Distinct from Governance Solutions.',
    howTo:
      'Open Contribute > Community Challenges. Use Create to start a challenge. Others can submit proposals; the coordinator selects one and runs implementation work as Opportunities.',
    routes: ['/contribute/challenges', '/contribute/challenges/new'],
    roles: ['member'],
    relatedCapabilities: ['projects', 'solution_records', 'opportunities', 'programs'],
    aliases: ['challenges', 'community problem-solving', 'problem solving lab'],
    sourceRefs: [
      'src/lib/challenges.ts',
      'src/pages/contribute/CommunityChallenges.tsx',
      'docs/04-operations/dev/contribute-page.md',
      'docs/04-operations/dev/phase-1-pilot-operating-model.md',
    ],
  },
  {
    id: 'matters',
    name: 'Questions, Issues & Ideas',
    status: 'implemented',
    description:
      'Generic Matter collaboration under Contribute. Ask a question, raise an issue, suggest an improvement, or work with others toward an outcome. Every active Matter shows who must act next, what is expected, when it is due, and what happens if nobody acts. Comments are not formal actions. When work is needed, the responsible party can start collaborative work, assign Tasks, record Decisions, and return to the same resolution confirmation flow. Completing a Task does not resolve the Matter. Ordinary collaborative-work completion requires required Tasks to be Completed or Cancelled; inviting someone to collaborate is not the same as asking them to accept shared responsibility. Authorized leads can add AI assistance, including a Coding Agent that uses a live model to inspect and edit authorized files through a trusted isolated worktree runner for human review — it does not commit, push, or deploy.',
    howTo:
      'Open Contribute > Questions, Issues & Ideas. Create a Matter, choose the intended person or organization, then follow the Current Action panel. For work that needs several people, use Start collaborative work. Needs Your Action also lists assigned Tasks.',
    routes: ['/contribute/matters', '/contribute/matters/new'],
    roles: ['member'],
    relatedCapabilities: ['contribute_hub'],
    aliases: ['matters', 'questions', 'issues', 'ideas', 'suggestions', 'requests', 'discussions'],
    sourceRefs: [
      'src/lib/matters.ts',
      'src/pages/contribute/Matters.tsx',
      'src/pages/contribute/MatterWorkPanel.tsx',
      'src/pages/contribute/MatterAgentPanel.tsx',
      'docs/04-operations/dev/matter-collaboration.md',
      'docs/04-operations/dev/contribute-page.md',
    ],
  },
  {
    id: 'projects',
    name: 'Projects',
    status: 'implemented',
    description:
      'Implementation records inside Community Challenges. There is no separate community-projects board. Contribute > Projects redirects to Challenges.',
    routes: ['/contribute/challenges'],
    roles: ['member'],
    relatedCapabilities: ['community_challenges', 'opportunities'],
    aliases: ['implementation project', 'community projects'],
    sourceRefs: ['docs/04-operations/dev/contribute-page.md', 'docs/04-operations/dev/phase-1-pilot-operating-model.md'],
  },
  {
    id: 'knowledge_spaces',
    name: 'Knowledge Spaces',
    status: 'implemented',
    description:
      'Learning Commons collections of practical resources. Distinct from Study and Governance Solutions.',
    howTo: 'Open Contribute > Learning Commons.',
    routes: ['/contribute/knowledge', '/contribute/knowledge/new'],
    roles: ['member'],
    relatedCapabilities: ['knowledge_gaps', 'solution_records', 'study'],
    aliases: ['learning commons', 'shared knowledge'],
    sourceRefs: [
      'src/lib/knowledge.ts',
      'src/pages/contribute/KnowledgeSpaces.tsx',
      'docs/04-operations/dev/contribute-page.md',
    ],
  },
  {
    id: 'knowledge_gaps',
    name: 'Knowledge Gaps',
    status: 'implemented',
    description:
      'Named gaps in a Knowledge Space. Coordinators can turn an actionable gap into an Opportunity or a Community Challenge.',
    routes: ['/contribute/knowledge'],
    roles: ['member'],
    relatedCapabilities: ['knowledge_spaces', 'opportunities', 'community_challenges'],
    aliases: ['gaps'],
    sourceRefs: ['src/lib/knowledge.ts', 'docs/04-operations/dev/contribute-page.md'],
  },
  {
    id: 'solution_records',
    name: 'Solution Records',
    status: 'implemented',
    description:
      'Outcome record created when a Community Challenge completes. May link a Human Outcome Review and a public-safe lesson. Negative or unclear human outcomes are preserved. Not a Happiness ranking and not Governance Solutions.',
    routes: ['/contribute/challenges'],
    roles: ['member'],
    relatedCapabilities: ['community_challenges', 'knowledge_spaces', 'governance_solutions'],
    aliases: ['challenge solution record'],
    sourceRefs: ['src/lib/challenges.ts', 'docs/04-operations/dev/contribute-page.md'],
  },
  {
    id: 'programs',
    name: 'Programs',
    status: 'implemented',
    description:
      'Containers for contribution work (education_to_contribution, community_problem_solving, shared_knowledge). Published by a profile.',
    routes: ['/contribute'],
    roles: ['member'],
    relatedCapabilities: ['opportunities', 'community_challenges', 'knowledge_spaces'],
    aliases: ['contribution programs'],
    sourceRefs: ['src/lib/challenges.ts', 'docs/04-operations/dev/phase-1-pilot-operating-model.md'],
  },
  {
    id: 'my_contributions',
    name: 'My Contributions',
    status: 'implemented',
    description: 'Your applications, completed work, and verified participations across opportunity kinds.',
    howTo: 'Open Contribute > My Contributions. Profile also shows the Contributions ledger.',
    routes: ['/contribute/impact', '/profile/contributions'],
    roles: ['member'],
    relatedCapabilities: ['opportunities', 'score'],
    aliases: ['impact', 'contribution ledger'],
    sourceRefs: ['src/pages/contribute/ContributeImpact.tsx', 'src/lib/contribute-lanes.ts'],
  },
  {
    id: 'contribute_improvements',
    name: 'Suggest Improvements',
    status: 'implemented',
    description:
      'Shortcut into Matter create as a Suggestion addressed to Civizen. Not a separate suggestion backend, and not a second place for Opportunities, Challenges, or shared knowledge.',
    howTo: 'Open Contribute > Suggest Improvements. It opens a new Matter already set as a Suggestion to Civizen. You can edit the type, recipient, and Area before submitting.',
    routes: ['/contribute/improvements', '/contribute/matters/new'],
    roles: ['member'],
    relatedCapabilities: ['contribute_hub', 'matters'],
    aliases: ['product suggestions'],
    sourceRefs: ['src/lib/contribute-lanes.ts', 'docs/04-operations/dev/contribute-page.md', 'docs/04-operations/dev/matter-collaboration.md'],
  },
  {
    id: 'market',
    name: 'Market',
    status: 'implemented',
    description:
      'Public Jobs board plus marketplace listings, products, and services. Anyone can look for work or post a job without an account. Contact details stay locked until sign-in. Start agreement or Contact for member listings. Ordinary orders use Marketplace terms.',
    howTo: 'Open Jobs from the public website, or Market > Jobs. The page title is Marketplace / Jobs. The sentence fills place from your location and shows a guide pay for the job type. Employers look for a person, not a job. Guests can browse and post there. Signed-in members can unfold More for work days, hours, languages, and notes.',
    routes: ['/jobs', '/market'],
    roles: ['guest', 'member'],
    relatedCapabilities: ['agreements', 'prototype_credits'],
    aliases: ['marketplace', 'listings'],
    sourceRefs: ['src/pages/Market.tsx', 'src/lib/main-nav.ts', 'docs/04-operations/dev/agreements.md', 'docs/04-operations/dev/market-jobs-public.md'],
  },
  {
    id: 'agreements',
    name: 'Agreements',
    status: 'implemented',
    description:
      'Platform workspace to create, review, sign, and keep agreements with people and organizations. Supported types open purpose-built documents (including Employment and Lease). Native electronic signing uses typed name plus explicit consent. Paper or external execution can be recorded. Not a certified PKI digital signature and not a claim of legal enforceability.',
    howTo:
      'Open Market > Agreements. Tap + beside the title, choose a type (Employment and Lease are in the common list; Lease includes Car, Vehicle, Residential, Commercial, Equipment, Office, and Property rental), edit the agreement document, create it, then propose and sign.',
    routes: ['/agreements', '/agreements/new'],
    roles: ['member', 'citizen', 'verified_member', 'certified', 'moderator', 'admin', 'founder'],
    relatedCapabilities: ['market', 'partnerships', 'opportunities'],
    aliases: ['contracts', 'sign agreement', 'e-sign', 'digital signature', 'collaboration agreement', 'employment agreement', 'lease', 'car lease', 'equipment lease', 'rental agreement'],
    sourceRefs: [
      'docs/04-operations/dev/agreements.md',
      'src/lib/agreements-model.ts',
      'src/lib/agreements-api.ts',
      'src/pages/Agreements.tsx',
      'src/lib/feature-registry.ts',
    ],
  },
  {
    id: 'messaging',
    name: 'Messaging',
    status: 'implemented',
    description:
      'Private conversations, including a pinned chat with Civi. Person-to-person chats can be hidden from your inbox (the other person keeps their copy). Disappearing messages is a shared thread setting both people see, applying to new messages. You can edit or unsend your own message for one minute. Civi chats can be cleared entirely. Searching for people can use phone contacts with permission; people not on Civizen can be invited. Optional device-based E2EE for person-to-person chat.',
    routes: ['/messaging'],
    roles: ['member'],
    relatedCapabilities: ['nela'],
    aliases: ['chat', 'dm', 'inbox'],
    sourceRefs: ['src/components/ui/chat-bar.tsx', 'src/lib/main-nav.ts'],
  },
  {
    id: 'nela',
    name: 'Civi',
    status: 'implemented',
    description:
      'Civi is Civizen’s AI assistant. Visitors can ask project questions without creating an account. Members also find Civi pinned in Messaging. Answers from current project knowledge for this build. When Civi does not already have a good answer and uses Gemini, it checks that reply and may remember it for similar questions later. Identity, the capability registry, and the cheat sheet still win. Personal records are not stored in Civi memory. During development, founders can review questions and replies at Settings > AI Agent.',
    howTo: 'Open the Civi button at the lower right, or Messaging after you sign in. Founders can review interaction history from Settings > AI Agent.',
    routes: ['/onboarding', '/messaging', '/settings/ai-agent'],
    roles: ['guest', 'member'],
    relatedCapabilities: ['messaging'],
    aliases: ['nela', 'civi', 'assistant', 'in-app assistant', 'ai assistant', 'your ai assistant'],
    sourceRefs: [
      'supabase/functions/messaging-agent-reply/index.ts',
      'src/lib/messaging-constants.ts',
      'src/components/public/PublicCiviWidget.tsx',
      'src/lib/assistant/learned-memory.ts',
      'src/pages/settings/AiAgentSettings.tsx',
    ],
  },
];
