import type { AssistantCapability } from '../types';

export const ASSISTANT_CAPABILITIES_PART_2: AssistantCapability[] = [
  {
    id: 'why_civizen_exists',
    name: 'Why Civizen Exists',
    status: 'implemented',
    description:
      'Public founding message: Civizen exists to help people unite around shared human responsibility, with practical systems for cooperation and peace. Unity does not require uniformity. Nations and cultures stay. Complementary world citizenship is a civic identity, not current legal nationality.',
    howTo: 'Open Why Civizen Exists from the public site, or ask Civi how we can stop wars or unite humanity.',
    routes: ['/why-this-exists'],
    roles: ['guest', 'member'],
    relatedCapabilities: ['study', 'contribute_hub', 'governance'],
    aliases: ['why this exists', 'why civizen', 'founding message', 'unite humanity'],
    sourceRefs: [
      'docs/00-foundation/why-civizen-exists-page-brief.md',
      'docs/00-foundation/recognized-planetary-citizenship-pathway.md',
      'docs/00-foundation/the-civizen-charter.md',
      'src/lib/assistant/peace.ts',
    ],
  },
  {
    id: 'profile',
    name: 'Profiles',
    status: 'implemented',
    description:
      'Member and linked business profiles with identity, education, experience, skills, endorsements, and Score. Optional Identity verification from Settings → Edit Profile uploads an ID photo and face photo for staff review when stronger trust is needed (not at signup; not a government ID).',
    howTo:
      'Open Profile from the menu. To verify identity when needed: Open Settings > Edit Profile, then use Identity verification to upload an ID photo and a face photo and submit for review.',
    routes: ['/profile', '/settings/profile'],
    roles: ['member'],
    relatedCapabilities: ['score', 'my_contributions', 'governance'],
    aliases: ['account', 'edit profile', 'identity verification', 'verify identity'],
    sourceRefs: [
      'src/lib/feature-registry.ts',
      'src/lib/identity-verification.ts',
      'docs/04-operations/dev/identity-verification-manual.md',
      'docs/assistant/civizen-assistant-cheatsheet.md',
    ],
  },
  {
    id: 'score',
    name: 'Civizen Score',
    status: 'implemented',
    description:
      'Score V2 with Learning, Experience, Skills, Performance, and Contributions. Public overall score is established activity. Tiers: Explorer, Builder, Contributor, Catalyst, Steward. Still in formation. Happiness data is not part of Score.',
    howTo: 'Open Profile or the Home Score card. Contributions detail is also under Profile > Contributions.',
    routes: ['/profile', '/profile/contributions'],
    roles: ['member'],
    relatedCapabilities: ['my_contributions', 'profile'],
    aliases: ['rating', 'reputation', 'civizen score v2'],
    sourceRefs: ['src/lib/civizen-score-model.ts', 'docs/03-platform/scoring-and-reputation/civizen-score-tiers-implementation.md'],
  },
  {
    id: 'happiness',
    name: 'Happiness & Fulfillment',
    status: 'implemented',
    description:
      'Private Happiness & Human Fulfillment. Five levels (Struggling, Unsettled, Balanced, Flourishing, Thriving) — not a numeric Happiness Score. Adaptive check-ins record today’s feeling, multiple life areas, and specific supports or problems; weekly pulse, monthly review, Fulfillment Plans under Improve, causes, and small actions with follow-up. Private by default. Not used for Score, reputation, hiring, or governance power. Work issues open Work Fulfillment. Actual employment uses Marketplace Jobs. Optional privacy-protected group insights are off by default and never show individual Happiness to employers. Civi may receive a grounded Plan brief; it must not invent history or diagnose. Follow-up timing can be stored; notifications are not sent yet.',
    howTo: 'Open Happiness & Fulfillment from the Profile menu. Check in from Overview or the Check-ins tab, review wellbeing, or Improve to start a Fulfillment Plan.',
    routes: ['/happiness', '/happiness/check-in', '/happiness/review', '/happiness/improve', '/happiness/privacy'],
    roles: ['member'],
    relatedCapabilities: ['work_fulfillment', 'study', 'opportunities', 'contribute_hub', 'market', 'wellbeing_aggregate'],
    aliases: ['wellbeing', 'happiness score', 'how am I doing', 'fulfillment'],
    sourceRefs: [
      'docs/03-platform/happiness-and-fulfillment/happiness-human-fulfillment-v1.md',
      'src/pages/happiness/Happiness.tsx',
      'src/lib/happiness/model.ts',
    ],
  },
  {
    id: 'work_fulfillment',
    name: 'Work Fulfillment',
    status: 'implemented',
    description:
      'Distinct Work Fulfillment & Occupational Fit subunit inside Happiness. Current work, Work Joy Monitor, Fit profile, improve-current-work first. Contribute is for trying work (Contribution Fit). Marketplace Jobs is for actual employment (Job Fit). Study for learning/reskill. Low work fulfillment does not automatically recommend a new career. No public Work Fulfillment or Job Fit score. Approved shareable preferences may prefill Jobs; private Joy, diagnoses, and notes never transfer.',
    howTo: 'Open Happiness & Fulfillment, then Work Fulfillment. For a job, open Market > Jobs.',
    routes: ['/happiness/work', '/market'],
    roles: ['member'],
    relatedCapabilities: ['happiness', 'study', 'opportunities', 'contribute_hub', 'market'],
    aliases: ['occupational fit', 'work joy', 'career fit'],
    sourceRefs: [
      'docs/03-platform/happiness-and-fulfillment/happiness-human-fulfillment-v1.md',
      'src/lib/work-fulfillment/types.ts',
      'src/pages/happiness/HappinessWork.tsx',
    ],
  },
  {
    id: 'wellbeing_aggregate',
    name: 'Wellbeing Insights',
    status: 'implemented',
    description:
      'Authorized viewers can open Wellbeing Insights and Human Outcome Reviews for privacy-protected group patterns. Individual Happiness stays private. Published lessons are Civizen-member readable after an intentional publish step, not anonymous internet access. There is no Happiness impact score, ranking, or causal claim from before-and-after observation.',
    howTo: 'Open Happiness & Fulfillment > Privacy, or Wellbeing Insights. After a linked Challenge, Project, or Governance action, use Human Outcome Review. Participation is off by default.',
    routes: ['/happiness/privacy', '/wellbeing-insights', '/wellbeing-insights/outcome'],
    roles: ['member'],
    relatedCapabilities: ['happiness'],
    aliases: ['anonymous happiness', 'employer wellbeing dashboard', 'organization happiness score', 'human outcome review'],
    sourceRefs: ['docs/03-platform/happiness-and-fulfillment/happiness-human-fulfillment-v1.md', 'src/pages/wellbeing/WellbeingInsights.tsx'],
  },
  {
    id: 'governance',
    name: 'Governance',
    status: 'implemented',
    description:
      'Public governance landing, civic voting, and one member Governance page with three tabs: Votes (open consultations with your own ballot status, scheduled ones, and published results), Proposals (drafts open for member support with a support threshold, your drafts, published and closed proposals), and Tools (steward console and legacy workspace tools, shown only to office holders, founders, admins, or members who can assign roles). A consultation starts as a Matter; its author opens the draft for member support, sets scope (global or one country) and opening/closing times, and can publish once the support threshold is reached; founders and admins can publish at any time. Ordinary consultations need only a free account; the server enforces sanctions, minimum age, verification and country scope when an election declares them. Every voter gets a receipt they can check against the public list of counted ballots; choices stay sealed. Members are notified when a consultation they follow is published and when its result is published. Current public community instrument is the Community Governance Charter.',
    howTo:
      'Open Home > Governance for the landing, Home > Governance > Civic voting for the public election catalog, and Settings > Member workspace (or /governance/workspace) for the member Governance page with the Votes, Proposals and Tools tabs. Start a consultation from a Matter (Contribute > Questions, Issues & Ideas > Create voting proposal), then open it for member support on the proposal page. Tap the bell in the top chrome or Settings > Notifications for notifications. The steward console is at /governance/tools/steward and the legacy workspace tools at /governance/tools (Tools tab).',
    routes: ['/governance', '/governance/workspace', '/governance/tools', '/governance/tools/steward', '/governance/voting', '/notifications'],
    roles: ['guest', 'member'],
    relatedCapabilities: ['governance_charter', 'civic_voting', 'governance_solutions'],
    aliases: ['civic governance', 'proposals'],
    sourceRefs: [
      'src/pages/governance/PublicGovernanceLanding.tsx',
      'docs/02-policies/governance/civizen-community-governance-charter.md',
    ],
  },
  {
    id: 'civic_voting',
    name: 'Civic voting',
    status: 'implemented',
    description:
      'Elections catalog, ballot pages, and an Observer console at /governance/voting. Public browsing is available; casting needs a free account. Ballot choices are sealed on the server and never shown individually; every voter gets a receipt (a code in groups of four) and can check it against the public list of counted receipts. Eligibility (sign-in, voting window, sanctions, and any verified-identity, minimum-age, or country rule the consultation declares) is checked on the server and the reason is shown when a member cannot vote. A ballot can be withdrawn and cast again until closing. Consultations close automatically at their closing time with a published tally and outcome (quorum, pass threshold, most chosen option, or the most approved option for approval ballots where voters pick several options). The Observer console shows countable and withdrawn ballots and audit events only. The first real public consultation is A Single World Citizenship: a global, nonbinding question on whether humanity should work toward a single world citizenship shared by all people regardless of nationality. Support, Oppose, and Abstain are equal. A Support vote does not create or grant citizenship. Token wealth does not create voting power.',
    howTo:
      'Open Home > Governance > Civic voting, open a consultation, choose an option, and keep the receipt shown afterwards. Use Check that my receipt is counted on the same page, Withdraw ballot to change your vote while voting is open, and Observe next to the title for process metrics.',
    routes: ['/governance/voting'],
    roles: ['guest', 'member'],
    relatedCapabilities: ['governance', 'notifications'],
    aliases: ['elections', 'vote', 'ballot', 'receipt', 'consultation', 'observer console'],
    sourceRefs: ['src/pages/governance/CivicVotingHub.tsx', 'docs/02-policies/governance/civizen-community-governance-charter.md'],
  },
  {
    id: 'notifications',
    name: 'Notifications',
    status: 'implemented',
    description:
      'Notification center for members: the bell at the top of the app shows the unread count and opens the Notifications page, which lists consultations you follow (published, result published), Matters, agreements, and posts that concern you. Each item opens the related page.',
    howTo: 'Tap the bell at the top of the app, or open Settings > Notifications.',
    routes: ['/notifications'],
    roles: ['member'],
    relatedCapabilities: ['governance', 'matters', 'agreements'],
    aliases: ['notification center', 'bell', 'bell icon', 'alerts'],
    sourceRefs: ['src/pages/Notifications.tsx', 'src/components/layout/NotificationBell.tsx', 'src/lib/notifications.ts'],
  },
  {
    id: 'help_support',
    name: 'Help and support',
    status: 'implemented',
    description:
      'Settings page that gathers where to get help: Ask Civi in Messaging, the public Documents, Why Civizen Exists, the legal status notice, and the Terms.',
    howTo: 'Open Settings > Help and support.',
    routes: ['/settings/help'],
    roles: ['member'],
    relatedCapabilities: ['nela'],
    aliases: ['help page', 'support page', 'get help'],
    sourceRefs: ['src/pages/settings/HelpSupport.tsx', 'src/pages/settings/help-support-links.ts'],
  },
  {
    id: 'governance_solutions',
    name: 'Governance Solutions',
    status: 'implemented',
    description:
      'Post a civic Problem and Discuss or Solve. AI council can participate in discussion. Distinct from Community Challenge Solution Records.',
    routes: ['/governance/solutions'],
    roles: ['member'],
    relatedCapabilities: ['governance', 'solution_records'],
    aliases: ['solutions hub', 'problem council'],
    sourceRefs: ['src/pages/governance/SolutionsHub.tsx', 'docs/04-operations/dev/solutions-council.md'],
  },
  {
    id: 'governance_charter',
    name: 'Civizen Community Governance Charter',
    status: 'implemented',
    description:
      'Current public community governance instrument (interim). Not a government constitution. Replaces Civizen Constitution v0.1.',
    routes: ['/governance/charter'],
    roles: ['guest', 'member'],
    relatedCapabilities: ['governance'],
    aliases: ['civizen constitution', 'constitution', 'charter'],
    sourceRefs: [
      'docs/02-policies/governance/civizen-community-governance-charter.md',
      'docs/01-governance/constitution/civizen-constitution-v0.1.md',
    ],
  },
  {
    id: 'areas',
    name: 'Areas',
    status: 'implemented',
    description:
      'Read-only public Areas V1: Health, Education, Culture, Responsibility, Environment. Shows where help is needed.',
    howTo: 'Open Areas from Contribute, Home > Governance, or the public footer.',
    routes: ['/areas'],
    roles: ['guest', 'member'],
    relatedCapabilities: ['partnerships', 'contribute_hub'],
    aliases: ['foundational areas', 'where help is needed'],
    sourceRefs: [
      'src/lib/areas/public-areas.ts',
      'docs/03-platform/areas-and-initiatives/public-areas-initiatives-v1.md',
    ],
  },
  {
    id: 'partnerships',
    name: 'Partnerships',
    status: 'implemented',
    description:
      'Public Partners notice for international partnerships and chapters. Institutional inquiries are under Contribute > Financial Support. Not a partner CRM.',
    routes: ['/partners', '/fund/institutional'],
    roles: ['guest', 'member'],
    relatedCapabilities: ['areas', 'funding', 'agreements'],
    aliases: ['organization partnership', 'chapters', 'institutions'],
    sourceRefs: [
      'docs/02-policies/institutional/international-partnerships-and-chapters.md',
      'src/lib/contribute-lanes.ts',
    ],
  },
  {
    id: 'funding',
    name: 'Funding',
    status: 'implemented',
    description:
      'Public inquiry hub only. Does not process investments, issue securities, or create binding investment agreements. Current public policy is Funding and Financial Integrity.',
    routes: ['/fund', '/fund/support', '/fund/invest', '/fund/transparency'],
    roles: ['guest', 'member'],
    relatedCapabilities: ['partnerships', 'tokenomics_governance'],
    aliases: ['donate', 'invest', 'support civizen'],
    sourceRefs: ['docs/02-policies/institutional/funding-and-financial-integrity.md', 'src/pages/fund/FundHub.tsx'],
  },
  {
    id: 'prototype_credits',
    name: 'Prototype credits',
    status: 'experimental',
    description:
      'Luma is a non-transferable prototype credit for demonstration. Not money, not a wallet for settlement, no governance rights. Peer send is disabled.',
    routes: ['/settings/prototype-credits'],
    roles: ['member'],
    relatedCapabilities: ['market', 'tokenomics_governance'],
    aliases: ['luma', 'luma wallet', 'wallet', 'lumens'],
    sourceRefs: ['src/lib/prototype-credits.ts', 'src/lib/feature-registry.ts'],
  },
  {
    id: 'luma_transfers',
    name: 'Luma transfers',
    status: 'deprecated',
    description: 'Peer Luma transfer and marketplace Luma checkout are disabled. Do not describe Luma as a working currency.',
    routes: ['/settings/prototype-credits'],
    roles: ['member'],
    relatedCapabilities: ['prototype_credits'],
    aliases: ['peer send luma', 'luma checkout'],
    sourceRefs: ['src/lib/prototype-credits.ts', 'src/lib/luma-transfer.ts'],
  },
  {
    id: 'tokenomics_governance',
    name: 'Constitutional Tokenomics + Governance Model',
    status: 'historical',
    description:
      'Earlier planning document. Not adopted. Not current policy. Not an implemented monetary system. Current public funding policy is Funding and Financial Integrity.',
    routes: ['/documents', '/fund'],
    roles: ['guest'],
    relatedCapabilities: ['funding', 'governance_charter', 'prototype_credits'],
    aliases: [
      'civizen constitutional tokenomics + governance model',
      'tokenomics',
      'funding constitution',
      'luma tokenomics',
    ],
    sourceRefs: [
      'docs/01-governance/funding-and-monetary/civizen-constitutional-tokenomics-governance.md',
      'docs/02-policies/institutional/funding-and-financial-integrity.md',
    ],
  },
  {
    id: 'institutional_blueprint',
    name: 'Institutional Blueprint',
    status: 'proposed',
    description:
      'Working institutional architecture (legal entities, funding allocation principles, authority). Project reference, not a live in-app government and not adopted public policy.',
    routes: [],
    roles: ['guest'],
    relatedCapabilities: ['governance'],
    aliases: ['institutional architecture'],
    sourceRefs: ['docs/institutional/institutional-blueprint.md'],
  },
  {
    id: 'phase1_pilots',
    name: 'Phase 1 contribution pilots',
    status: 'implemented',
    description:
      'Three live pilots: Education-to-Contribution, Community Problem-Solving Lab, and Shared Knowledge / Learning Commons.',
    routes: ['/contribute/professional', '/contribute/challenges', '/contribute/knowledge'],
    roles: ['member'],
    relatedCapabilities: ['opportunities', 'community_challenges', 'knowledge_spaces'],
    aliases: ['pilots', 'phase 1'],
    sourceRefs: ['docs/04-operations/dev/phase-1-pilot-operating-model.md'],
  },
];
