blank_issues_enabled: true
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/Gityer/civizen/security/advisories/new
    about: Please report vulnerabilities privately.
