import { render } from '@testing-library/react';
import { type ComponentType } from 'react';

export type PageEntry = {
  name: string;
  path: string;
  routePath?: string;
  load: () => Promise<{ default: ComponentType<Record<string, never>> }>;
};

/** Every routed page module — import smoke catches missing default exports. */
export const allPages: PageEntry[] = [
  { name: 'Home', path: '/', load: () => import('@/pages/Home') },
  { name: 'NotFound', path: '/missing-route', load: () => import('@/pages/NotFound') },
  { name: 'Login', path: '/login', load: () => import('@/pages/auth/Login') },
  { name: 'SignUp', path: '/signup', load: () => import('@/pages/auth/SignUp') },
  { name: 'ForgotPassword', path: '/forgot-password', load: () => import('@/pages/auth/ForgotPassword') },
  { name: 'ResetPassword', path: '/reset-password', load: () => import('@/pages/auth/ResetPassword') },
  { name: 'Contribute', path: '/contribute', load: () => import('@/pages/Contribute') },
  {
    name: 'MatterFormImprovement',
    path: '/contribute/matters/new?intent=improvement',
    load: () => import('@/pages/contribute/MatterForm'),
  },
  { name: 'ProfessionalOpportunities', path: '/contribute/professional', load: () => import('@/pages/contribute/ProfessionalOpportunities') },
  { name: 'OpportunityForm', path: '/contribute/professional/new', load: () => import('@/pages/contribute/OpportunityForm') },
  { name: 'OpportunityDetail', path: '/contribute/professional/opp-1', routePath: '/contribute/professional/:opportunityId', load: () => import('@/pages/contribute/OpportunityDetail') },
  { name: 'CommunityChallenges', path: '/contribute/challenges', load: () => import('@/pages/contribute/CommunityChallenges') },
  { name: 'ChallengeForm', path: '/contribute/challenges/new', load: () => import('@/pages/contribute/ChallengeForm') },
  { name: 'ChallengeDetail', path: '/contribute/challenges/ch-1', routePath: '/contribute/challenges/:challengeId', load: () => import('@/pages/contribute/ChallengeDetail') },
  { name: 'KnowledgeSpaces', path: '/contribute/knowledge', load: () => import('@/pages/contribute/KnowledgeSpaces') },
  { name: 'KnowledgeSpaceForm', path: '/contribute/knowledge/new', load: () => import('@/pages/contribute/KnowledgeSpaceForm') },
  { name: 'KnowledgeSpaceDetail', path: '/contribute/knowledge/space-1', routePath: '/contribute/knowledge/:spaceId', load: () => import('@/pages/contribute/KnowledgeSpaceDetail') },
  { name: 'KnowledgeResourceForm', path: '/contribute/knowledge/space-1/resources/new', routePath: '/contribute/knowledge/:spaceId/resources/new', load: () => import('@/pages/contribute/KnowledgeResourceForm') },
  { name: 'KnowledgeResourceDetail', path: '/contribute/knowledge/space-1/resources/res-1', routePath: '/contribute/knowledge/:spaceId/resources/:resourceId', load: () => import('@/pages/contribute/KnowledgeResourceDetail') },
  { name: 'ContributeImpact', path: '/contribute/impact', load: () => import('@/pages/contribute/ContributeImpact') },
  { name: 'Matters', path: '/contribute/matters', load: () => import('@/pages/contribute/Matters') },
  { name: 'MatterForm', path: '/contribute/matters/new', load: () => import('@/pages/contribute/MatterForm') },
  { name: 'MatterDetail', path: '/contribute/matters/mat-1', routePath: '/contribute/matters/:matterId', load: () => import('@/pages/contribute/MatterDetail') },
  { name: 'Messaging', path: '/messaging', load: () => import('@/pages/Messaging') },
  { name: 'WhyThisExists', path: '/why-this-exists', load: () => import('@/pages/WhyThisExists') },
  { name: 'Areas', path: '/areas', load: () => import('@/pages/Areas') },
  { name: 'AreaDetail', path: '/areas/education', routePath: '/areas/:slug', load: () => import('@/pages/AreaDetail') },
  { name: 'Features', path: '/features', load: () => import('@/pages/Features') },
  { name: 'Law', path: '/law', load: () => import('@/pages/Law') },
  { name: 'Market', path: '/market', load: () => import('@/pages/Market') },
  { name: 'MarketTaxonomy', path: '/market/taxonomy', load: () => import('@/pages/MarketTaxonomy') },
  { name: 'Agreements', path: '/agreements', load: () => import('@/pages/Agreements') },
  { name: 'AgreementCreate', path: '/agreements/new', load: () => import('@/pages/AgreementCreate') },
  { name: 'AgreementDetail', path: '/agreements/demo', routePath: '/agreements/:id', load: () => import('@/pages/AgreementDetail') },
  { name: 'Earnings', path: '/earnings', load: () => import('@/pages/Earnings') },
  { name: 'Happiness', path: '/happiness', load: () => import('@/pages/happiness/Happiness') },
  { name: 'HappinessCheckIn', path: '/happiness/check-in', load: () => import('@/pages/happiness/HappinessCheckIn') },
  { name: 'HappinessReview', path: '/happiness/review', load: () => import('@/pages/happiness/HappinessReview') },
  { name: 'HappinessImprove', path: '/happiness/improve', load: () => import('@/pages/happiness/HappinessImprove') },
  { name: 'HappinessWork', path: '/happiness/work', load: () => import('@/pages/happiness/HappinessWork') },
  { name: 'HappinessPrivacy', path: '/happiness/privacy', load: () => import('@/pages/happiness/HappinessPrivacy') }, { name: 'WellbeingInsights', path: '/wellbeing-insights', load: () => import('@/pages/wellbeing/WellbeingInsights') }, { name: 'HumanOutcomeReview', path: '/wellbeing-insights/outcome', load: () => import('@/pages/wellbeing/HumanOutcomeReview') },
  { name: 'TermsOfUse', path: '/terms', load: () => import('@/pages/TermsOfUse') },
  { name: 'Search', path: '/search', load: () => import('@/pages/Search') },
  { name: 'Profile', path: '/profile', load: () => import('@/pages/Profile') },
  { name: 'ContributionsLedger', path: '/profile/contributions', load: () => import('@/pages/profile/ContributionsLedger') },
  { name: 'UserProfile', path: '/u/founder', routePath: '/u/:username', load: () => import('@/pages/UserProfile') },
  { name: 'EndorseSelect', path: '/endorse', load: () => import('@/pages/EndorseSelect') },
  { name: 'EndorseFlow', path: '/endorse/demo', routePath: '/endorse/:userId', load: () => import('@/pages/EndorseFlow') },
  { name: 'Governance', path: '/governance/workspace', load: () => import('@/pages/Governance') },
  { name: 'GovernanceNew', path: '/governance/new', load: () => import('@/pages/GovernanceNew') },
  { name: 'PublicGovernanceLanding', path: '/governance', load: () => import('@/pages/governance/PublicGovernanceLanding') },
  { name: 'CivicVotingHub', path: '/governance/voting', load: () => import('@/pages/governance/CivicVotingHub') },
  { name: 'CivicVotingElection', path: '/governance/voting/e1', routePath: '/governance/voting/:electionId', load: () => import('@/pages/governance/CivicVotingElection') },
  { name: 'CivicVotingObserver', path: '/governance/voting/e1/observe', routePath: '/governance/voting/:electionId/observe', load: () => import('@/pages/governance/CivicVotingObserver') },
  { name: 'SolutionsHub', path: '/governance/solutions', load: () => import('@/pages/governance/SolutionsHub') },
  { name: 'SolutionProblemDetail', path: '/governance/solutions/p1', routePath: '/governance/solutions/:problemId', load: () => import('@/pages/governance/SolutionProblemDetail') },
  { name: 'Study', path: '/study', load: () => import('@/pages/Study') },
  { name: 'StudyLayout', path: '/study/layout', load: () => import('@/pages/StudyLayout') },
  { name: 'StudyCivicLearning', path: '/study/civic', load: () => import('@/pages/study/StudyCivicLearning') },
  { name: 'StudySpecialists', path: '/study/specialists', load: () => import('@/pages/study/StudySpecialists') },
  { name: 'StudyCourses', path: '/study/courses', load: () => import('@/pages/study/StudyCourses') },
  { name: 'StudySchedules', path: '/study/schedules', load: () => import('@/pages/study/StudySchedules') },
  { name: 'StudyMaterials', path: '/study/materials', load: () => import('@/pages/study/StudyMaterials') },
  { name: 'StudyTests', path: '/study/tests', load: () => import('@/pages/study/StudyTests') },
  { name: 'FundHub', path: '/fund', load: () => import('@/pages/fund/FundHub') },
  { name: 'FundSupport', path: '/fund/support', load: () => import('@/pages/fund/FundSupport') },
  { name: 'FundInvest', path: '/fund/invest', load: () => import('@/pages/fund/FundInvest') },
  { name: 'FundInstitutional', path: '/fund/institutional', load: () => import('@/pages/fund/FundInstitutional') },
  { name: 'FundContribute', path: '/fund/contribute', load: () => import('@/pages/fund/FundContribute') },
  { name: 'FundTransparency', path: '/fund/transparency', load: () => import('@/pages/fund/FundTransparency') },
  { name: 'FundProjectFinance', path: '/fund/project-finance', load: () => import('@/pages/fund/FundProjectFinance') },
  { name: 'PublicDocumentsIndex', path: '/documents', load: () => import('@/pages/institutional/PublicDocumentsIndex') },
  { name: 'InstitutionalDocRoute', path: '/documents/legal-status', routePath: '/documents/:slug', load: () => import('@/pages/institutional/InstitutionalDocRoute') },
  { name: 'Pillars', path: '/settings/pillars', load: () => import('@/pages/settings/Pillars') },
  { name: 'Professions', path: '/settings/professions', load: () => import('@/pages/settings/Professions') },
  { name: 'RolesAdmin', path: '/settings/admin/roles', load: () => import('@/pages/settings/RolesAdmin') },
  { name: 'UsersAdmin', path: '/settings/admin/users', load: () => import('@/pages/settings/UsersAdmin') },
  { name: 'PermissionsAdmin', path: '/settings/admin/permissions', load: () => import('@/pages/settings/PermissionsAdmin') },
  { name: 'GovernanceAdmin', path: '/settings/admin/governance', load: () => import('@/pages/settings/GovernanceAdmin') },
  { name: 'LumaCreditsAdmin', path: '/settings/admin/luma', load: () => import('@/pages/settings/LumaCreditsAdmin') },
  { name: 'FundingAdmin', path: '/settings/admin/funding', load: () => import('@/pages/settings/FundingAdmin') },
  { name: 'FundingInterestAdmin', path: '/settings/admin/funding/interest', load: () => import('@/pages/settings/FundingInterestAdmin') },
  { name: 'FundingLedgerAdmin', path: '/settings/admin/funding/ledger', load: () => import('@/pages/settings/FundingLedgerAdmin') },
  { name: 'FundingAuditAdmin', path: '/settings/admin/funding/audit', load: () => import('@/pages/settings/FundingAuditAdmin') },
  { name: 'FundingComplianceAdmin', path: '/settings/admin/funding/compliance', load: () => import('@/pages/settings/FundingComplianceAdmin') },
  { name: 'FundingContributorsAdmin', path: '/settings/admin/funding/contributors', load: () => import('@/pages/settings/FundingContributorsAdmin') },
  { name: 'PrototypeCredits', path: '/settings/prototype-credits', load: () => import('@/pages/settings/PrototypeCredits') },
  { name: 'Taxonomy', path: '/settings/taxonomy', load: () => import('@/pages/settings/Taxonomy') },
  { name: 'MessagingSettings', path: '/settings/messaging', load: () => import('@/pages/settings/MessagingSettings') },
  { name: 'MessagingSecurity', path: '/settings/messaging-security', load: () => import('@/pages/settings/MessagingSecurity') },
  { name: 'PrivacySettings', path: '/settings/privacy', load: () => import('@/pages/settings/PrivacySettings') },
  { name: 'AiAgentSettings', path: '/settings/ai-agent', load: () => import('@/pages/settings/AiAgentSettings') },
  { name: 'SocialAccountsSettings', path: '/settings/social-accounts', load: () => import('@/pages/settings/SocialAccountsSettings') },
];

/**
 * High-risk entry points where missing imports caused boot crashes.
 * Full render catches ReferenceErrors that import-only cannot.
 */
