import { lazyWithChunkReload } from '@/lib/lazy-with-chunk-reload';

// Pages (lazy-loaded to keep bundle sizes small). lazyWithChunkReload auto-recovers
// when a deploy removes hashed chunks the open tab still references.
export const Onboarding = lazyWithChunkReload(() => import('@/pages/Onboarding'));
export const Login = lazyWithChunkReload(() => import('@/pages/auth/Login'));
export const SignUp = lazyWithChunkReload(() => import('@/pages/auth/SignUp'));
export const ForgotPassword = lazyWithChunkReload(() => import('@/pages/auth/ForgotPassword'));
export const ResetPassword = lazyWithChunkReload(() => import('@/pages/auth/ResetPassword'));
export const Contribute = lazyWithChunkReload(() => import('@/pages/Contribute'));
export const ContributeLane = lazyWithChunkReload(() => import('@/pages/ContributeLane'));
export const ProfessionalOpportunities = lazyWithChunkReload(
  () => import('@/pages/contribute/ProfessionalOpportunities'),
);
export const OpportunityDetail = lazyWithChunkReload(() => import('@/pages/contribute/OpportunityDetail'));
export const OpportunityForm = lazyWithChunkReload(() => import('@/pages/contribute/OpportunityForm'));
export const CommunityChallenges = lazyWithChunkReload(() => import('@/pages/contribute/CommunityChallenges'));
export const ChallengeForm = lazyWithChunkReload(() => import('@/pages/contribute/ChallengeForm'));
export const ChallengeDetail = lazyWithChunkReload(() => import('@/pages/contribute/ChallengeDetail'));
export const KnowledgeSpaces = lazyWithChunkReload(() => import('@/pages/contribute/KnowledgeSpaces'));
export const KnowledgeSpaceForm = lazyWithChunkReload(() => import('@/pages/contribute/KnowledgeSpaceForm'));
export const KnowledgeSpaceDetail = lazyWithChunkReload(() => import('@/pages/contribute/KnowledgeSpaceDetail'));
export const KnowledgeResourceForm = lazyWithChunkReload(() => import('@/pages/contribute/KnowledgeResourceForm'));
export const KnowledgeResourceDetail = lazyWithChunkReload(() => import('@/pages/contribute/KnowledgeResourceDetail'));
export const ContributeImpact = lazyWithChunkReload(() => import('@/pages/contribute/ContributeImpact'));
export const Matters = lazyWithChunkReload(() => import('@/pages/contribute/Matters'));
export const MatterForm = lazyWithChunkReload(() => import('@/pages/contribute/MatterForm'));
export const MatterDetail = lazyWithChunkReload(() => import('@/pages/contribute/MatterDetail'));
export const Messaging = lazyWithChunkReload(() => import('@/pages/Messaging'));
export const DownloadPage = lazyWithChunkReload(() => import('@/pages/Download'));
export const WhyThisExists = lazyWithChunkReload(() => import('@/pages/WhyThisExists'));
export const Areas = lazyWithChunkReload(() => import('@/pages/Areas'));
export const AreaDetail = lazyWithChunkReload(() => import('@/pages/AreaDetail'));
export const FundHub = lazyWithChunkReload(() => import('@/pages/fund/FundHub'));
export const FundSupport = lazyWithChunkReload(() => import('@/pages/fund/FundSupport'));
export const FundInvest = lazyWithChunkReload(() => import('@/pages/fund/FundInvest'));
export const FundInstitutional = lazyWithChunkReload(() => import('@/pages/fund/FundInstitutional'));
export const FundContribute = lazyWithChunkReload(() => import('@/pages/fund/FundContribute'));
export const FundTransparency = lazyWithChunkReload(() => import('@/pages/fund/FundTransparency'));
export const FundProjectFinance = lazyWithChunkReload(() => import('@/pages/fund/FundProjectFinance'));
export const PublicDocumentsIndex = lazyWithChunkReload(() => import('@/pages/institutional/PublicDocumentsIndex'));
export const InstitutionalDocRoute = lazyWithChunkReload(() => import('@/pages/institutional/InstitutionalDocRoute'));
export const Features = lazyWithChunkReload(() => import('@/pages/Features'));
export const StudyLayout = lazyWithChunkReload(() => import('@/pages/StudyLayout'));
export const StudyCivicLearning = lazyWithChunkReload(() => import('@/pages/study/StudyCivicLearning'));
export const StudySpecialists = lazyWithChunkReload(() => import('@/pages/study/StudySpecialists'));
export const StudyCourses = lazyWithChunkReload(() => import('@/pages/study/StudyCourses'));
export const StudySchedules = lazyWithChunkReload(() => import('@/pages/study/StudySchedules'));
export const StudyMaterials = lazyWithChunkReload(() => import('@/pages/study/StudyMaterials'));
export const StudyTests = lazyWithChunkReload(() => import('@/pages/study/StudyTests'));
export const Governance = lazyWithChunkReload(() => import('@/pages/Governance'));
export const GovernanceNew = lazyWithChunkReload(() => import('@/pages/GovernanceNew'));
export const PublicGovernanceLanding = lazyWithChunkReload(() => import('@/pages/governance/PublicGovernanceLanding'));
export const CivicVotingHub = lazyWithChunkReload(() => import('@/pages/governance/CivicVotingHub'));
export const CivicVotingProposal = lazyWithChunkReload(() => import('@/pages/governance/CivicVotingProposal'));
export const CivicVotingElection = lazyWithChunkReload(() => import('@/pages/governance/CivicVotingElection'));
export const CivicVotingObserver = lazyWithChunkReload(() => import('@/pages/governance/CivicVotingObserver'));
export const SolutionsHub = lazyWithChunkReload(() => import('@/pages/governance/SolutionsHub'));
export const SolutionProblemDetail = lazyWithChunkReload(() => import('@/pages/governance/SolutionProblemDetail'));
export const Home = lazyWithChunkReload(() => import('@/pages/Home'));
export const Law = lazyWithChunkReload(() => import('@/pages/Law'));
export const Market = lazyWithChunkReload(() => import('@/pages/Market'));
export const MarketTaxonomy = lazyWithChunkReload(() => import('@/pages/MarketTaxonomy'));
export const Agreements = lazyWithChunkReload(() => import('@/pages/Agreements'));
export const AgreementCreate = lazyWithChunkReload(() => import('@/pages/AgreementCreate'));
export const AgreementDetail = lazyWithChunkReload(() => import('@/pages/AgreementDetail'));
export const Earnings = lazyWithChunkReload(() => import('@/pages/Earnings'));
export const TermsOfUse = lazyWithChunkReload(() => import('@/pages/TermsOfUse'));
export const Search = lazyWithChunkReload(() => import('@/pages/Search'));
export const Profile = lazyWithChunkReload(() => import('@/pages/Profile'));
export const ContributionsLedger = lazyWithChunkReload(() => import('@/pages/profile/ContributionsLedger'));
export const UserProfile = lazyWithChunkReload(() => import('@/pages/UserProfile'));
export const EndorseFlow = lazyWithChunkReload(() => import('@/pages/EndorseFlow'));
export const Settings = lazyWithChunkReload(() => import('@/pages/Settings'));
export const EditProfile = lazyWithChunkReload(() => import('@/pages/settings/EditProfile'));
export const Pillars = lazyWithChunkReload(() => import('@/pages/settings/Pillars'));
export const Professions = lazyWithChunkReload(() => import('@/pages/settings/Professions'));
export const RolesAdmin = lazyWithChunkReload(() => import('@/pages/settings/RolesAdmin'));
export const UsersAdmin = lazyWithChunkReload(() => import('@/pages/settings/UsersAdmin'));
export const PermissionsAdmin = lazyWithChunkReload(() => import('@/pages/settings/PermissionsAdmin'));
export const GovernanceAdmin = lazyWithChunkReload(() => import('@/pages/settings/GovernanceAdmin'));
export const LumaCreditsAdmin = lazyWithChunkReload(() => import('@/pages/settings/LumaCreditsAdmin'));
export const FundingAdmin = lazyWithChunkReload(() => import('@/pages/settings/FundingAdmin'));
export const DevEconomicsVisual = import.meta.env.DEV
  ? lazyWithChunkReload(() => import('@/pages/dev/DevEconomicsVisual'))
  : null;
export const WalletPage = lazyWithChunkReload(() => import('@/pages/settings/PrototypeCredits'));
export const TaxonomySettings = lazyWithChunkReload(() => import('@/pages/settings/Taxonomy'));
export const MessagingSettingsPage = lazyWithChunkReload(() => import('@/pages/settings/MessagingSettings'));
export const MessagingSecurity = lazyWithChunkReload(() => import('@/pages/settings/MessagingSecurity'));
export const PrivacySettings = lazyWithChunkReload(() => import('@/pages/settings/PrivacySettings'));
export const NotificationsSettings = lazyWithChunkReload(() => import('@/pages/settings/NotificationsSettings'));
export const SafetySettings = lazyWithChunkReload(() => import('@/pages/settings/SafetySettings'));
export const ModerationConsole = lazyWithChunkReload(() => import('@/pages/settings/ModerationConsole'));
export const HelpSupport = lazyWithChunkReload(() => import('@/pages/settings/HelpSupport'));
export const ReportContent = lazyWithChunkReload(() => import('@/pages/ReportContent'));
export const EndorseSelect = lazyWithChunkReload(() => import('@/pages/EndorseSelect'));
export const AiAgentSettings = lazyWithChunkReload(() => import('@/pages/settings/AiAgentSettings'));
export const SocialAccountsSettings = lazyWithChunkReload(() => import('@/pages/settings/SocialAccountsSettings'));
export const NotFound = lazyWithChunkReload(() => import('@/pages/NotFound'));
