-- Phase 0 trust hardening (S1): members could change every column of their own profile row, including
-- role, permission overrides, verified/civic flags and identity numbers, because the UPDATE policy only
-- checked ownership. Privileged columns may now change only through server functions (SECURITY DEFINER,
-- service role) or by staff holding role.assign / settings.manage. Ordinary profile edits are untouched.
--
-- A self-registered row (direct INSERT by the member) always starts from the default civic state.

CREATE OR REPLACE FUNCTION public.guard_profile_privileged_columns()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  -- current_user is 'authenticated' / 'anon' only for direct PostgREST writes. Inside SECURITY DEFINER
  -- functions it is the function owner, and service-role requests run as 'service_role'.
  v_direct_client boolean := current_user IN ('authenticated', 'anon');
BEGIN
  IF NOT v_direct_client THEN
    RETURN NEW;
  END IF;

  IF public.has_permission('role.assign'::public.app_permission)
     OR public.has_permission('settings.manage'::public.app_permission) THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    NEW.role := 'member';
    NEW.is_admin := false;
    NEW.custom_permissions := '{}'::public.app_permission[];
    NEW.granted_permissions := '{}'::public.app_permission[];
    NEW.denied_permissions := '{}'::public.app_permission[];
    NEW.is_verified := false;
    NEW.citizenship_status := 'registered_member';
    NEW.citizenship_accepted_at := NULL;
    NEW.citizenship_acceptance_mode := NULL;
    NEW.citizenship_review_cleared_at := NULL;
    NEW.is_active_citizen := false;
    NEW.active_citizen_since := NULL;
    NEW.is_governance_eligible := false;
    NEW.governance_eligible_at := NULL;
    NEW.is_system_agent := false;
    NEW.experience_level := 'entry';
    NEW.official_id := NULL;              -- regenerated by prepare_profile_identity
    NEW.social_security_number := NULL;   -- regenerated by prepare_profile_identity
    NEW.deleted_at := NULL;
    NEW.deletion_reason := NULL;
    RETURN NEW;
  END IF;

  IF NEW.user_id IS DISTINCT FROM OLD.user_id
     OR NEW.role IS DISTINCT FROM OLD.role
     OR NEW.is_admin IS DISTINCT FROM OLD.is_admin
     OR NEW.custom_permissions IS DISTINCT FROM OLD.custom_permissions
     OR NEW.granted_permissions IS DISTINCT FROM OLD.granted_permissions
     OR NEW.denied_permissions IS DISTINCT FROM OLD.denied_permissions
     OR NEW.is_verified IS DISTINCT FROM OLD.is_verified
     OR NEW.citizenship_status IS DISTINCT FROM OLD.citizenship_status
     OR NEW.citizenship_accepted_at IS DISTINCT FROM OLD.citizenship_accepted_at
     OR NEW.citizenship_acceptance_mode IS DISTINCT FROM OLD.citizenship_acceptance_mode
     OR NEW.citizenship_review_cleared_at IS DISTINCT FROM OLD.citizenship_review_cleared_at
     OR NEW.is_active_citizen IS DISTINCT FROM OLD.is_active_citizen
     OR NEW.active_citizen_since IS DISTINCT FROM OLD.active_citizen_since
     OR NEW.is_governance_eligible IS DISTINCT FROM OLD.is_governance_eligible
     OR NEW.governance_eligible_at IS DISTINCT FROM OLD.governance_eligible_at
     OR NEW.is_system_agent IS DISTINCT FROM OLD.is_system_agent
     OR NEW.experience_level IS DISTINCT FROM OLD.experience_level
     OR NEW.official_id IS DISTINCT FROM OLD.official_id
     OR NEW.social_security_number IS DISTINCT FROM OLD.social_security_number
     OR NEW.deleted_at IS DISTINCT FROM OLD.deleted_at
     OR NEW.deletion_reason IS DISTINCT FROM OLD.deletion_reason THEN
    RAISE EXCEPTION 'profile_privileged_column_change_forbidden'
      USING ERRCODE = '42501',
            HINT = 'Role, permissions, verification, civic status and identity numbers change only through staff tools or server functions.';
  END IF;

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.guard_profile_privileged_columns() IS
  'BEFORE INSERT/UPDATE guard on profiles: direct client writes by non-staff cannot change role, permissions, verification, civic status, identity numbers or deletion state.';

-- Named to run before the other BEFORE triggers on profiles (alphabetical order), so derived columns
-- set by later triggers (is_admin, citizenship projection) are never mistaken for a client change.
DROP TRIGGER IF EXISTS aaa_guard_profile_privileged_columns ON public.profiles;
CREATE TRIGGER aaa_guard_profile_privileged_columns
  BEFORE INSERT OR UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.guard_profile_privileged_columns();
